### ISSUE TITLE
Not an issue, more of a question

### ISSUE THREAD

**Issue by zero-pytagoras** [mrutkowski2904/ili9341-linux-driver#1]
Hi,
I am wondering to know, if i'd like to compile this driver for X86 or x86_64 or amd64 will this work ? do i need any controller board ? seeking for guidance mostly

**Comment by mrutkowski2904** [comment]
Hi, 
It should work, but you would have to create dts file with hw configuration, and then pass it's compiled version (dtb) to the kernel during boot. I think GRUB supports that on x86/x86_64.

Hardware wise, you would need SPI controller on your board and one free GPIO, this GPIO must assigned to `dc-gpios` property in dts (display uses this GPIO to differentiate between data and configuration transfers.

**Comment by zero-pytagoras** [comment]
where can i get dtb driver ? I have spi controller, and its driver compiles without any errors. but this one usually gives me error of `undefined`. I working on rocky linux 9.3 with SElinux disabled, kernel 5.14.0, with all the possible development libraries installed, here are print screens of the issue, before tweaking and after tweaking:

![e1](https://github.com/mrutkowski2904/ili9341-linux-display-driver/assets/91202914/8cf0c36f-71f6-4f93-a5b6-68e24dbf83f5)

![e2](https://github.com/mrutkowski2904/ili9341-linux-display-driver/assets/91202914/04327d54-b8b8-4d1c-85b5-4589aeb853a1)


by tweaking i mean manually getting libraries and putting on the places they are required by the `make`

**Comment by mrutkowski2904** [comment]
It appears that you are using different driver for this display than mine. I can see errors related to mipi interface and drm framework, none of which, my driver uses.
To build any driver, you need to download linux source code (or linux-headers for currently running kernel) and point the build system to it.

For dtb, you first need to write proper dts that matches your system's hardware, then using device tree compiler you have to compile it to dtb.
I have only used dtb on embedded systems, that don't use GRUB, so you need to do your own reasearch on how to pass it to the kernel on x86 PC.
